### ISSUE TITLE
[EVE-33] Race condition in ESDB subscriptions with random NullReferenceException

### ISSUE THREAD

**Issue by diegosasw** [Eventuous/eventuous#181]
**Describe the bug**
Integration tests for an app using Eventuous 0.13.1 fail randomly when running in parallel.

Error is
```
System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Eventuous.EventStore.Subscriptions.EventStoreCatchUpSubscriptionBase`1..ctor(EventStoreClient eventStoreClient, T options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)
   at Eventuous.EventStore.Subscriptions.AllStreamSubscription..ctor(EventStoreClient eventStoreClient, AllStreamSubscriptionOptions options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Sometimes it occurs on some test, sometimes on another, sometimes it doesn't.

All the tests (i.e: [Fact]) instantiate a TestServer because the test classes inherit from base class
```
public abstract class FunctionalTest
{
    protected HttpClient HttpClient { get; }
    
    protected FunctionalTest()
    {
        var webApplicationFactory =
            new WebApplicationFactory<Program>()
                .WithWebHostBuilder(webHostBuilder => webHostBuilder.UseEnvironment("Development"));
        
        HttpClient = webApplicationFactory.CreateClient();
    }
}
```

**Could not yet reproduce in a GitLab runner.**

**To Reproduce**
1. Clone this repository https://gitlab.com/sunnyatticsoftware/sample/eventuous-modular-race-condition-tests
2. Run ESDB and MongoDb in local
   ```
   docker run \
      --name esdb \
      -p 2113:2113 \
      -p 1113:1113 \
      eventstore/eventstore:22.10.0-buster-slim \
      --insecure \
      --enable-atom-pub-over-http \
      --mem-db=True
   ```
  and
   ```
   docker run \
      --name mongo \
      --mount type=tmpfs,destination=/data/db \
      -e MONGO_INITDB_ROOT_USERNAME=root \
      -e MONGO_INITDB_ROOT_PASSWORD=dummy \
      -p 27017:27017 \
      mongo:4.0
   ```
   NOTE: This requires some entries in `/etc/hosts`. 
   ```
   # Local servers
   127.0.0.1   eventstoredb
   127.0.0.1   mongodb

   ```
   If pointing to localhost, edit `appsettings.json` and replace `eventstoredb` and `mongodb` with `localhost`.
3. Run `dotnet test`

**Expected behavior**
Tests to pass always

**Actual behavior**
Tests randomly fail when running in parallel (by default in xUnit).

Sample:
```
dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Modular.Clients -> /media/diegosasw/data/src/sandbox/eventuous-modular-race-condition-tests/src/client/Modular.Clients/bin/Debug/net7.0/Modular.Clients.dll
  Modular.ClientsInfo -> /media/diegosasw/data/src/sandbox/eventuous-modular-race-condition-tests/src/client-info/Modular.ClientsInfo/bin/Debug/net7.0/Modular.ClientsInfo.dll
  Modular.Api -> /media/diegosasw/data/src/sandbox/eventuous-modular-race-condition-tests/src/Modular.Api/bin/Debug/net7.0/Modular.Api.dll
  Modular.Api.FunctionalTests -> /media/diegosasw/data/src/sandbox/eventuous-modular-race-condition-tests/test/Modular.Api.FunctionalTests/bin/Debug/net7.0/Modular.Api.FunctionalTests.dll
Test run for /media/diegosasw/data/src/sandbox/eventuous-modular-race-condition-tests/test/Modular.Api.FunctionalTests/bin/Debug/net7.0/Modular.Api.FunctionalTests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:01.41]     Modular.Api.FunctionalTests.AnotherTests.Three [FAIL]
[13:58:40 INF] Call failed with gRPC error status. Status code: 'Cancelled', Message: 'Call canceled by the client.'. <s:Grpc.Net.Client.Internal.GrpcCall>
[13:58:40 DBG] Starting subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:40 DBG] Type ClientCreated registered as V1.ClientCreated <s:eventuous>
[13:58:40 DBG] Type ClientCreated registered as V1.ClientCreated <s:eventuous>
[13:58:40 DBG] Type ClientAdminCredentialsUpdated registered as V1.ClientAdminCredentialsUpdated <s:eventuous>
[13:58:40 DBG] Type ClientAdminCredentialsUpdated registered as V1.ClientAdminCredentialsUpdated <s:eventuous>
[13:58:40 DBG] Starting subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:41 INF] [projections] Loaded checkpoint projections from MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
[13:58:41 INF] [projections] Loaded checkpoint projections from MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
[13:58:41 INF] [projections] Started <s:Eventuous.Subscription>
[13:58:41 INF] [projections] Started <s:Eventuous.Subscription>
[13:58:41 INF] Started subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:41 INF] Started subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:41 INF] [projections] Stored checkpoint projections in MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
[13:58:41 INF] [projections] Stored checkpoint projections in MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
[13:58:41 INF] Route matched with {action = "Get", controller = "Health"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller Modular.Api.Controllers.HealthController (Modular.Api). <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] Route matched with {action = "Get", controller = "Health"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller Modular.Api.Controllers.HealthController (Modular.Api). <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] Executing OkObjectResult, writing value of type 'System.String'. <s:Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor>
[13:58:41 INF] Executing OkObjectResult, writing value of type 'System.String'. <s:Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor>
[13:58:41 INF] Executed action Modular.Api.Controllers.HealthController.Get (Modular.Api) in 11.2942ms <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] Executed action Modular.Api.Controllers.HealthController.Get (Modular.Api) in 11.2955ms <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] HTTP GET /health responded 200 in 36.7654 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 INF] HTTP GET /health responded 200 in 36.8072 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 INF] HTTP GET /health responded 200 in 69.0459 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 INF] HTTP GET /health responded 200 in 69.0513 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 DBG] Type ClientCreated registered as V1.ClientCreated <s:eventuous>
[13:58:41 DBG] Type ClientCreated registered as V1.ClientCreated <s:eventuous>
[13:58:41 DBG] Type ClientAdminCredentialsUpdated registered as V1.ClientAdminCredentialsUpdated <s:eventuous>
[13:58:41 DBG] Type ClientAdminCredentialsUpdated registered as V1.ClientAdminCredentialsUpdated <s:eventuous>
[13:58:41 DBG] Type ClientCreated registered as V1.ClientCreated <s:eventuous>
[13:58:41 DBG] Type ClientCreated registered as V1.ClientCreated <s:eventuous>
[13:58:41 DBG] Type ClientAdminCredentialsUpdated registered as V1.ClientAdminCredentialsUpdated <s:eventuous>
[13:58:41 DBG] Type ClientAdminCredentialsUpdated registered as V1.ClientAdminCredentialsUpdated <s:eventuous>
[13:58:41 DBG] Starting subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:41 DBG] Starting subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:41 INF] [projections] Loaded checkpoint projections from MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
[13:58:41 INF] [projections] Loaded checkpoint projections from MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
[13:58:41 INF] [projections] Started <s:Eventuous.Subscription>
[13:58:41 INF] Started subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:41 INF] [projections] Started <s:Eventuous.Subscription>
[13:58:41 INF] Started subscription projections <s:Eventuous.Subscriptions.SubscriptionHostedService>
[13:58:41 INF] Route matched with {action = "Get", controller = "Health"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller Modular.Api.Controllers.HealthController (Modular.Api). <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] Executing OkObjectResult, writing value of type 'System.String'. <s:Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor>
[13:58:41 INF] Route matched with {action = "Get", controller = "Health"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller Modular.Api.Controllers.HealthController (Modular.Api). <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] Executed action Modular.Api.Controllers.HealthController.Get (Modular.Api) in 1.0113ms <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] HTTP GET /health responded 200 in 4.1970 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 INF] HTTP GET /health responded 200 in 6.7394 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 INF] Executing OkObjectResult, writing value of type 'System.String'. <s:Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor>
[13:58:41 INF] Executed action Modular.Api.Controllers.HealthController.Get (Modular.Api) in 0.2744ms <s:Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker>
[13:58:41 INF] HTTP GET /health responded 200 in 1.8965 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 INF] HTTP GET /health responded 200 in 3.5090 ms <s:Serilog.AspNetCore.RequestLoggingMiddleware>
[13:58:41 INF] [projections] Stored checkpoint projections in MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
[13:58:41 INF] [projections] Stored checkpoint projections in MongoCheckpointStore: Checkpoint { Id = projections, Position = 733 } <s:Eventuous.Subscription>
  Failed Modular.Api.FunctionalTests.AnotherTests.Three [1 ms]
  Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at Eventuous.EventStore.Subscriptions.EventStoreCatchUpSubscriptionBase`1..ctor(EventStoreClient eventStoreClient, T options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)
   at Eventuous.EventStore.Subscriptions.AllStreamSubscription..ctor(EventStoreClient eventStoreClient, AllStreamSubscriptionOptions options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Failed!  - Failed:     1, Passed:     4, Skipped:     0, Total:     5, Duration: 520 ms - Modular.Api.FunctionalTests.dll (net7.0)
```

<sub>[EVE-33](https://linear.app/eventuous/issue/EVE-33/race-condition-in-esdb-subscriptions-with-random)</sub>

**Comment by diegosasw** [comment]
I've made each test to use its own MongoDb Database and EventStoreDb Streamname to see if the problem had anything to do with shared resources (e.g: the checkpoint collection in a database, or similar), but the problem remains (see [the repo](https://gitlab.com/sunnyatticsoftware/sample/eventuous-modular-race-condition-tests) that reproduces the problem)

I still get the same `Object reference not set to an instance of an object.
   at Eventuous.EventStore.Subscriptions.EventStoreCatchUpSubscriptionBase`1..ctor(EventStoreClient eventStoreClient, T options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)`

at zero, one or more tests randomly.

**Comment by diegosasw** [comment]
It's definitely something related to the `services.AddSubscription<AllStreamSubscription, AllStreamSubscriptionOptions>(...)`, because the problem is not reproduced when not adding any subscription.

Also, assigning a different subscription Id to each subscription (i.e: to each TestServer instantiation/launching) doesn't make any difference.

If I de-register all the `IHostedService` immediately after `AddSubscription`, then the errors don't happen.

So, probably it's something related to the fact that the `SubscriptionRegistrationExtensions` has a delayed instantiation of `SubscriptionHostedService`?

If I look at Eventuous implementation, the `IHostedService` is not registered as a specific implementation but as a delegate. Could that be the cause of a race condition?

```
// 
return services
            .AddSubscriptionBuilder(builder)
            .AddSingleton(sp => GetBuilder(sp).ResolveSubscription(sp))
            .AddSingleton<IHostedService>(
                sp =>
                    new SubscriptionHostedService(
                        GetBuilder(sp).ResolveSubscription(sp),
                        sp.GetService<ISubscriptionHealth>(),
                        sp.GetService<ILoggerFactory>()
                    )
            );
```


Is the error due to the `ILoggerFactory` being `null` in `Eventuous.EventStore.Subscriptions.AllStreamSubscription..ctor(EventStoreClient eventStoreClient, AllStreamSubscriptionOptions options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)`?

Not sure which one is the parameter causing the `NullReferenceException` because the logs don't say.

**Comment by alexeyzimarev** [comment]
Subscriptions should tolerate the logger factory being null, it's a nullable argument, and there are coalescing everywhere (supposedly).

**Comment by alexeyzimarev** [comment]
Can't you set a breakpoint in the constructor base call to see where it crashes?

**Comment by diegosasw** [comment]
It never crashes when debugging all so it won't hit breakpoints. But I found that the problem happens when resolving the `IHostedService`, which is registered as a delegate in `SubscriptionRegistrationExtensions.cs`

It's the messageSubscrition resolving what's causing it. Something to do with reflection.
```
var messageSubscription = GetBuilder(sp).ResolveSubscription(sp);
```

I could capture the exception making this changes at `AddSubscription<T, TOptions>(...)`
```
return services
    .AddSubscriptionBuilder(builder)
    .AddSingleton(sp => GetBuilder(sp).ResolveSubscription(sp))
    .AddSingleton<IHostedService>(
        sp => {
            try {
                var messageSubscription = GetBuilder(sp).ResolveSubscription(sp); // here it crashes SOMETIMES when running in parallel
                var subscriptionHealth = sp.GetService<ISubscriptionHealth>();
                var loggerFactory = sp.GetService<ILoggerFactory>();
                
                var hostedService =
                    new SubscriptionHostedService(
                        messageSubscription,
                        subscriptionHealth,
                        loggerFactory);

                return hostedService;
            }
            catch (Exception exception) {
                throw new Exception("Gotcha", exception);
            }
        }
    );
```

now gives more details on what's going on. It seems the root cause is losing the exception trace because it's happening when the DependencyInjection tries to resolve the `IHostedService`.

Here's the full log
```
System.Exception: Gotcha

System.Exception
Gotcha
   at Microsoft.Extensions.DependencyInjection.SubscriptionRegistrationExtensions.<>c__DisplayClass0_0`2.<AddSubscription>b__1(IServiceProvider sp) in /media/diegosasw/data/src/sandbox/eventuous/src/Core/src/Eventuous.Subscriptions/Registrations/SubscriptionRegistrationExtensions.cs:line 56
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args) in /media/diegosasw/data/src/sandbox/eventuous/src/Sample/src/Modular.Api/Program.cs:line 60
   at InvokeStub_Program.<Main>$(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.DeferredHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DelegatedWebApplicationFactory.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()
   at Modular.Api.FunctionalTests.TestSupport.FunctionalTest..ctor() in /media/diegosasw/data/src/sandbox/eventuous/src/Sample/test/Modular.Api.FunctionalTests/TestSupport/FunctionalTest.cs:line 26
   at Modular.Api.FunctionalTests.AnotherTests..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.InvokeWithManyArguments(RuntimeConstructorInfo ci, Int32 argCount, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Eventuous.Subscriptions.Registrations.SubscriptionBuilder`2.ResolveSubscription(IServiceProvider sp) in /media/diegosasw/data/src/sandbox/eventuous/src/Core/src/Eventuous.Subscriptions/Registrations/SubscriptionBuilder.cs:line 218
   at Microsoft.Extensions.DependencyInjection.SubscriptionRegistrationExtensions.<>c__DisplayClass0_0`2.<AddSubscription>b__1(IServiceProvider sp) in /media/diegosasw/data/src/sandbox/eventuous/src/Core/src/Eventuous.Subscriptions/Registrations/SubscriptionRegistrationExtensions.cs:line 43

System.NullReferenceException
Object reference not set to an instance of an object.
   at Eventuous.EventStore.Subscriptions.EventStoreCatchUpSubscriptionBase`1..ctor(EventStoreClient eventStoreClient, T options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory) in /media/diegosasw/data/src/sandbox/eventuous/src/EventStore/src/Eventuous.EventStore/Subscriptions/EventStoreCatchUpSubscriptionBase.cs:line 19
   at Eventuous.EventStore.Subscriptions.AllStreamSubscription..ctor(EventStoreClient eventStoreClient, AllStreamSubscriptionOptions options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory) in /media/diegosasw/data/src/sandbox/eventuous/src/EventStore/src/Eventuous.EventStore/Subscriptions/AllStreamSubscription.cs:line 67
   at InvokeStub_AllStreamSubscription..ctor(Object, Object, IntPtr*)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Hopefully this makes more sense to you than to me :smiley:  

PS: I forked eventuous, and added my own branch with eventuous + Sample where I can reproduce the issue
https://github.com/diegosasw/eventuous/tree/issues/181

**Comment by alexeyzimarev** [comment]
The only reason it can crash is that the options argument is null:

```
    protected EventStoreCatchUpSubscriptionBase(
        EventStoreClient eventStoreClient,
        T                options,
        ICheckpointStore checkpointStore,
        ConsumePipe      consumePipe,
        ILoggerFactory?  loggerFactory
    ) : base(options, checkpointStore, consumePipe, options.ConcurrencyLimit, loggerFactory)
        => EventStoreClient = eventStoreClient;
```

Here's the only place that accesses anything inside the argument: `options.ConcurrencyLimit`.

I don't think it's related to the hosted service or the builder as it crashes in the EventStoreCatchUpSubscriptionBase constructor according to the stack trace.

**Comment by alexeyzimarev** [comment]
I will add a check if the options object is empty before doing anything else.

**Comment by alexeyzimarev** [comment]
There's no such thing as race condition when dependencies are being resolved. You don't see it crashing when you remove hosted services from the container as the subscription doesn't start, and, therefore, it's not being resolved, so all the DI-related code doesn't execute.

Honestly, I don't have any idea why it would not work.

**Comment by alexeyzimarev** [comment]
The last alpha will double-check that the options argument is not null, just to confirm (or not) that it is an issue.

**Comment by diegosasw** [comment]
Tried with 0.14.1-alpha.0.7. The issue must come from somewhere else but it manifests there.

Running tests separately or with parallelization disabled with
```
[assembly: CollectionBehavior(CollectionBehavior.CollectionPerClass, DisableTestParallelization = true)]
```
avoids the problem, but unfortunately when running in parallel it still fails randomly with this exception.

```
System.ArgumentNullException: Value cannot be null. (Parameter 'options')

System.ArgumentNullException
Value cannot be null. (Parameter 'options')
   at Eventuous.EventStore.Subscriptions.EventStoreCatchUpSubscriptionBase`1..ctor(EventStoreClient eventStoreClient, T options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)
   at Eventuous.EventStore.Subscriptions.AllStreamSubscription..ctor(EventStoreClient eventStoreClient, AllStreamSubscriptionOptions options, ICheckpointStore checkpointStore, ConsumePipe consumePipe, ILoggerFactory loggerFactory)
   at InvokeStub_AllStreamSubscription..ctor(Object, Object, IntPtr*)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

EDIT: **Alejandro-SB changes solves the mysterious issue!**
